import { PrinterProtocol, PrinterTransport } from './protocols.js';

/** Product-planning metadata, not a claim that every model supports every option. Verify its manual. */
export const protocolCatalog = Object.freeze([
  { protocol: PrinterProtocol.ESC_POS, uses: ['receipt', 'pos', 'kiosk', 'mobile'], manufacturers: ['Epson', 'Bixolon', 'Citizen', 'many compatibles'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'public/vendor', proprietary: false, tier: 'mvp', difficulty: 'medium' },
  { protocol: PrinterProtocol.ESC_X, uses: ['receipt', 'pos'], manufacturers: ['Epson'], rawBytes: true, transports: [PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'vendor', proprietary: true, tier: 'future', difficulty: 'high' },
  { protocol: PrinterProtocol.STAR_PRNT, uses: ['receipt', 'pos', 'kiosk'], manufacturers: ['Star Micronics'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.BLE, PrinterTransport.USB, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'vendor SDK', proprietary: true, tier: 'mvp', difficulty: 'medium' },
  { protocol: PrinterProtocol.STAR_RASTER, uses: ['receipt', 'pos'], manufacturers: ['Star Micronics'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.USB, PrinterTransport.TCP], androidDirect: true, documentation: 'vendor', proprietary: true, tier: 'future', difficulty: 'high' },
  { protocol: PrinterProtocol.ZPL, uses: ['label', 'industrial-label', 'mobile'], manufacturers: ['Zebra', 'ZPL-compatible vendors'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.BLE, PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'public/vendor', proprietary: true, tier: 'mvp', difficulty: 'medium' },
  { protocol: PrinterProtocol.EPL, uses: ['label', 'mobile'], manufacturers: ['Zebra/Eltron legacy'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'public/vendor', proprietary: true, tier: 'future', difficulty: 'medium' },
  { protocol: PrinterProtocol.CPCL, uses: ['mobile', 'label', 'receipt'], manufacturers: ['Zebra mobile'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.BLE, PrinterTransport.USB, PrinterTransport.TCP], androidDirect: true, documentation: 'public/vendor', proprietary: true, tier: 'mvp', difficulty: 'medium' },
  { protocol: PrinterProtocol.TSPL, uses: ['label', 'industrial-label'], manufacturers: ['TSC', 'TSPL-compatible vendors'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'public/vendor', proprietary: true, tier: 'future', difficulty: 'medium' },
  { protocol: PrinterProtocol.DPL, uses: ['label', 'industrial-label'], manufacturers: ['Honeywell/Datamax-O\'Neil'], rawBytes: true, transports: [PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'vendor', proprietary: true, tier: 'future', difficulty: 'high' },
  { protocol: PrinterProtocol.SBPL, uses: ['label', 'industrial-label'], manufacturers: ['SATO'], rawBytes: true, transports: [PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'vendor', proprietary: true, tier: 'future', difficulty: 'high' },
  { protocol: PrinterProtocol.IPL, uses: ['label', 'industrial-label', 'mobile'], manufacturers: ['Honeywell/Intermec'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER], androidDirect: true, documentation: 'vendor', proprietary: true, tier: 'future', difficulty: 'high' },
  { protocol: PrinterProtocol.ESC_P, uses: ['dot-matrix', 'legacy'], manufacturers: ['Epson and compatibles'], rawBytes: true, transports: [PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.WINDOWS_SPOOLER], androidDirect: 'model-dependent', documentation: 'public/vendor', proprietary: false, tier: 'experimental', difficulty: 'high' },
  { protocol: PrinterProtocol.ESC_P2, uses: ['dot-matrix', 'legacy'], manufacturers: ['Epson'], rawBytes: true, transports: [PrinterTransport.USB, PrinterTransport.WINDOWS_SPOOLER], androidDirect: 'model-dependent', documentation: 'vendor', proprietary: true, tier: 'experimental', difficulty: 'high' },
  { protocol: PrinterProtocol.RASTER_GENERIC, uses: ['vendor-specific', 'mobile', 'receipt'], manufacturers: ['varies'], rawBytes: true, transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.BLE, PrinterTransport.USB, PrinterTransport.SERIAL], androidDirect: 'model-dependent', documentation: 'varies', proprietary: 'varies', tier: 'experimental', difficulty: 'high' },
  { protocol: PrinterProtocol.VENDOR_SPECIFIC, uses: ['vendor-specific', 'mobile', 'receipt', 'label'], manufacturers: ['vendor-specific'], rawBytes: 'varies', transports: [PrinterTransport.BLUETOOTH_CLASSIC, PrinterTransport.BLE, PrinterTransport.USB, PrinterTransport.SERIAL, PrinterTransport.TCP, PrinterTransport.WINDOWS_SPOOLER, PrinterTransport.ANDROID_PRINT_FRAMEWORK], androidDirect: 'SDK/model-dependent', documentation: 'varies', proprietary: true, tier: 'experimental', difficulty: 'high' },
]);

export function protocolProfile(protocol) { return protocolCatalog.find(entry => entry.protocol === protocol); }
